version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres-diploma-api
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_DB: DiplomaApi
    ports:
      - 5432:5432
